'use strict';

module.exports = {
  is_claimed: null,
  rating: null,
  mobile_url: null,
  rating_img_url: null,
  review_count: null,
  name: null,
  rating_img_url_small: null,
  url: null,
  categories: [
    [null, null],
    [null, null],
    [null, null],
    [null, null],
    [null, null],
  ],
  phone: null,
  location: {
    cross_streets: null,
    city: null,
    display_address: [
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    geo_accuracy: null,
    neighborhoods: [
      null,
      null,
      null,
    ],
    postal_code: null,
    country_code: null,
    address: [
      null,
      null,
      null,
    ],
    coordinate: {
      latitude: null,
      longitude: null,
    },
    state_code: null,
  },
  display_phone: null,
  rating_img_url_large: null,
  id: null,
  is_closed: null,
  distance: null,
  cluster: null,
  section: null,
  index: null,
  datetime: null,
};
